name: sheet to json
on: 
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"
    
jobs:
  generate-json:
    name: rest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install
        
      - name: Generate index.js
        run: node sheet-to-json_generic.js

      - name: Git Status
        run: git status

      - name: Git Pull
        run: git pull


      - name: Commit files
        run: |
          git config --local user.email adityaparsad01@gmail.com
          git config --local user.name "adityaparsad01"
          git add .
          git commit -m "file update: json" || exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

#          git add /home/runner/work/RESTAPI/RESTAPI/faq.json
